name: Checks

on: [push, pull_request]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ^1.20
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Run Docker compose to spin up services
        run: docker compose up -d

      - name: Wait for postgres to be ready
        run: while ! pg_isready -h localhost -p 5432 -U postgres; do sleep 1; done

      - name: Run migrations
        run: for file in sql/*.sql; do psql "postgres://postgres:postgres@localhost:5432/postgres?sslmode=disable" -f $file; done

      - name: Run unit tests and generate the coverage report
        run: make test-race

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.21.6
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Install gofumpt
        run: go install mvdan.cc/gofumpt@v0.5.0

      - name: Install staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@2023.1.7

      - name: Install golangci-lint
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.57.2

      - name: Lint
        run: make lint

      - name: Ensure go mod tidy runs without changes
        run: |
          go mod tidy
          git diff-index HEAD
          git diff-index --quiet HEAD
